services:
  web:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: camagru-web
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - camagru-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: camagru-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - camagru-network

networks:
  camagru-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local